//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoviesDBEntities : DbContext
    {
        public MoviesDBEntities()
            : base("name=MoviesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Directors> Directors { get; set; }
        public virtual DbSet<loginUser> loginUser { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<Ratings> Ratings { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
