//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Publish_Date { get; set; }
        public string Creation_Date { get; set; }
        public int Director_Id { get; set; }
        public int Rating_Id { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Directors Directors { get; set; }
        public virtual Ratings Ratings { get; set; }
    }
}
